### ISSUE TITLE
Update to target Android 13

### ISSUE THREAD

**Issue by zello-eugene** [zelloptt/zello-android-sdk#28]
- [ ] Update target Android 13
- [ ] Update dependencies
- [ ] Update tools

**Comment by jpvasconcellos** [comment]
@zello-eugene can we close this ticket? Seems to me the work was already done:

```
	ext.appBuildToolsVersion = "33.0.0"
	ext.appCompileSdkVersion = 33
	ext.appTargetSdkVersion = 33

```
